name: SecretLab Coding Exercise

on: [push]

jobs:
  code-test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Composer
        run: |
          composer update
          composer dump-autoload
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Configuration application
        run: |
          cp .env.sai .env
          php artisan config:cache
          php artisan config:clear
          php artisan cache:clear
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test
